[package]
name = "rustw"
version = "0.1.0"
authors = ["Nick Cameron <ncameron@mozilla.com>"]
repository = "https://github.com/nrc/rustw"
readme = "README.md"
license = "Apache-2.0/MIT"
build = "build.rs"
categories = ["development-tools"]

[[bin]]
name = "rustw"

[[bin]]
name = "cargo-src"

[dependencies]
derive-new = "0.3"
url = "0.5"
getopts = "0.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
toml = "0.4"
rls-analysis = "0.10"
rls-span = "0.4"
rls-vfs = "0.4.4"
log = "0.3"
env_logger = "0.3"
rustdoc-highlight = { git = "https://github.com/nrc/rustdoc-highlight" }

[dependencies.hyper]
version = "0.8"
default-features = false

[build-dependencies]
walkdir = "0.1"
